spring.application.name=userservice
server.port=8081
spring.cassandra.keyspace-name=ecommerce
spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1