spring.application.name=order-service
server.port=8083

spring.cassandra.keyspace-name=ecommerce
spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1

spring.kafka.bootstrap-servers=localhost:9092
